### ISSUE TITLE
Pinned tags not showing on left bar

### ISSUE THREAD

**Issue by den7007** [linuxserver/docker-papermerge#29]
## Expected Behavior

Pinned tags will show up in the left bar under "Documents"

![Screenshot 2021-03-03 105447](https://user-images.githubusercontent.com/68644291/109745541-ffec6180-7c0e-11eb-9631-d233df65e88a.png)

## Current Behavior

No pinned tags are displayed or shown

![Screenshot 2021-03-03 105511](https://user-images.githubusercontent.com/68644291/109745543-0084f800-7c0f-11eb-8731-2dc3deeb07c5.png)

## Steps to Reproduce

I have followed set up via docker-compose as per instructions. I have tried deleting container and volume and reinstalling.

## Environment
**OS:** Raspbian
**CPU architecture:** arm64
**How docker service was installed:** From the official docker repo
```
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
```

## Command used to create docker container (run/create/compose/screenshot)
I used the docker-compose set up as mentioned in the instructions
```
version: "2.1"
services:
  papermerge:
    image: ghcr.io/linuxserver/papermerge
    container_name: papermerge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - REDIS_URL= #optional
    volumes:
      - /docker/papermerge/config:/config
      - /docker/papermerge/data:/data
    ports:
      - 8000:8000
    restart: unless-stopped
```

The app works as expected otherwise, but wondering why my pinned tags aren't showing up.
