### ISSUE TITLE
 OCR works only in root path

### ISSUE THREAD

**Issue by Animizio** [linuxserver/docker-papermerge#41]
**Description**
When uploading a file in papermerge it should start ocr. This is different from root or a folder path.
Upload it in root path works fine, but uploading into a folder does not use any ocr for that file.

**Expected**
ocr for every file uploaded, in root and also in folder paths

**Actual**
only ocr in root path. does not ocr when uploaded into a folder path.

**Info:**
 - OS: Docker, Synology NAS DS920+
 - Browser Firefox
 - Papermerge Version 2.0

**Comment by j0nnymoe** [comment]
Please provide the info that was requested in the issue template.

**Comment by Animizio** [comment]
## Expected Behavior
 ocr for every file uploaded, in root and also in folder paths

## Current Behavior
 only ocr in root path. does not ocr when uploaded into a folder path.

## Steps to Reproduce


1. upload a file in root
2. upload a file in a folder
3. the file in root will get ocr'ed
4.the file in a folder wont get ocr'ed

## Environment
**OS: SynologyNAS DS920+
**How docker service was installed:**
Installed it through the docker ui in the SynologyNAS

## Command used to create docker container (run/create/compose/screenshot)
![grafik](https://user-images.githubusercontent.com/25159989/152778735-0ef2c754-a679-4c22-89de-407895e3731d.png)
![grafik](https://user-images.githubusercontent.com/25159989/152778768-9652d59a-ec6c-46d7-96e3-eda20fb2e157.png)
![grafik](https://user-images.githubusercontent.com/25159989/152778802-3f8cf4af-5441-4d36-aa5b-194acad044ae.png)
![grafik](https://user-images.githubusercontent.com/25159989/152778871-5dc1fc47-cdbc-489e-8365-3845a0ea43f1.png)


## Docker logs

**Comment by Animizio** [comment]
docker logs:
[papermerge(1).csv](https://github.com/linuxserver/docker-papermerge/files/8014793/papermerge.1.csv)

**Comment by Animizio** [comment]
After i started from scratch and installed everything again it works now. #closed

**Comment by nsar1907** [comment]
can you please share your set up ?

i did everything and ocr language is only english so far and cant any other languaes


```
---
version: "2.1"
services:
  papermerge:
    image: lscr.io/linuxserver/papermerge:latest
    container_name: papermerge
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Germany/Berlin
      - REDIS_URL= #optional
      - DOCKER_MODS=linuxserver/mods:papermerge-multilangocr
      - OCRLANG="eng,deu,tur"
    volumes:
      - /volume2/docker/papermerge/config:/config
      - /volume2/docker/papermerge:/data
    ports:
      - 8005:8000
    restart: unless-stopped
```
