### ISSUE TITLE
v2.0.1-ls54 seems to be broken (v2.0.1-ls53 is working)

### ISSUE THREAD

**Issue by wisewtf** [linuxserver/docker-papermerge#43]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Current Behavior
Container isn't booting properly. The image seems to be broken.

We tried on discord on multiple hosts, no dice.

## Environment
**OS:** Alpine/Ubuntu/Debian
**CPU architecture:** x86_64
**How docker service was installed:**
From official repos on Debian systems and from the Alpine repos on Alpine.

## Command used to create docker container (run/create/compose/screenshot)
I tried deploying the stack with Portainer, and also via a compose file.

```yaml
---
version: "2.1"
services:
  papermerge:
    image: lscr.io/linuxserver/papermerge:latest
    container_name: papermerge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - /opt/docker/papermerge/config:/config
      - /opt/docker/papermerge/data:/data
    ports:
      - 8001:8000
    restart: unless-stopped
```

## Docker logs
Attached

[_papermerge_logs.log](https://github.com/linuxserver/docker-papermerge/files/9120803/_papermerge_logs.log)

Python exceptions go on a loop.
