### ISSUE TITLE
Tags are not submitted.

### ISSUE THREAD

**Issue by Nollknolle** [linuxserver/docker-papermerge#46]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Tags set at pressing Enter.

## Current Behavior

If you press enter it submits. Worked bevore.
https://user-images.githubusercontent.com/62543404/179423321-fa47b1a8-cf37-4604-94d1-2e11f3bcafc4.mp4
## Steps to Reproduce

1. Got to Automates
2. Create one and try to add a tag
3.
4.

## Environment
**OS:** Linux
**CPU architecture:** x86_64
**How docker service was installed:** From the GHRC Repo

## Command used to create docker container (run/create/compose/screenshot)

```
version: "2.1"
services:
  papermerge:
    image: lscr.io/linuxserver/papermerge:latest
    container_name: papermerge
    environment:
      - TZ=Europe/Berlin
      - DOCKER_MODS=linuxserver/mods:papermerge-multilangocr
      - OCRLANG="deu"
      - PUID=1000
      - PGID=1000
    volumes:
      - /share/papermerge-data/config:/config
      - /share/papermerge-data/data:/data
      - /share/papermerge:/import
    ports:
      - 8000:8000
    restart: unless-stopped
```

## Docker logs

[_papermerge_logs.txt](https://github.com/linuxserver/docker-papermerge/files/9128468/_papermerge_logs.txt)
